config:
  partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:    
    fabric-dev:
      authentication: CLI
      database: CargoWise_Lake
      driver: 'ODBC Driver 18 for SQL Server'
      host: akvrvmas2c4uhgg6sauqhzjzea-n4ww3rltqhwebmhltwb4edzhni.datawarehouse.pbidedicated.windows.net
      schema: cargowise_dk_wrld
      threads: 4
      type: fabric
      trust_cert: false